services:
  zion-bot:
    container_name: zion-discord-bot
    image: docker.io/ibfleming/zion-discord-bot:latest
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TZ=America/Los_Angeles
